# Site settings
title: Solomon's Blog
description: A personal blog
author: Solomon Oladiran
email:
baseurl: ""
url: "https://solomon-os.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
future: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excerpt settings
excerpt_separator: <!--more-->

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
